title: Le blog de rmathot
email:
description: >-
  L'informatique, le monde et ma cuisine.
baseurl: ""
url: "https://rmathot.github.io"
lang: fr_BE
locale: fr_BE
twitter_username: RichardMathot
github_username:  rmathot

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
