title: Le blog de rmathot
email: noone@nowhere.example.com
description: >-
  Un autre blog perso.
baseurl: ""
url: "https://rmathot.github.io"
twitter_username: RichardMathot
github_username:  rmathot

theme: minima
plugins:
  - jekyll-feed
